- name: Enable EPEL Repository
  hosts: allservers
  order: sorted
  become: True
  become_user: root
  tasks:
    - name: Install EPEL7 Repository
      yum:
        name: 'epel-release'
        state: latest