- name: Install MariaDB 10.2 server
  hosts: centos-node5.random.com
  order: sorted
  gather_facts: True
  become: True
  become_user: root
  vars_files:
    - vars/secrets.yml
  vars:
   root_remote: True
   test_database: True
   anonymous_disable: True
   host_name: "{{ inventory_hostname }}"
  tasks:
    - name: Install MariaDB Repository
      yum_repository:
        name: mariadb
        description: MariaDB Repository
        baseurl: http://yum.mariadb.org/10.2/centos7-amd64
        gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
        gpgcheck: yes
        includepkgs: MariaDB*
#
    - name: Install mariadb server
      yum:
        name:
         - MariaDB-server
         - MariaDB-common
         - MariaDB-client
         - MariaDB-backup
         - MariaDB-compat
         - MySQL-python
        enablerepo: mariadb,base,updates,extras,epel
        state: latest
#
    - name: Check and enable MySQL service
      service:
        name: mysql
        state: started
        enabled: true
#
    - name: Remove test database
      mysql_db:
        name: test
        state: absent
      when: test_database
#
    - name: Remove test database records from mysql db
      command: 'mysql -ne "{{ item }}"'
      with_items:
        - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
      changed_when: False
      when: test_database
#
    - name: Remove anonymous user
      mysql_user:
        name: ''
        host_all: yes
        state: absent
      when: anonymous_disable
#
    - name: Remove root remote login
      mysql_user: name=root host={{ host_name }} state=absent
      when: root_remote
#
    - name: Add .my.cnf with root password
      template: src=templates/my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600
#
    - name: Set root Password for localhost
      mysql_user: check_implicit_admin=yes name=root host={{ item }} password={{ root_db_password }} state=present
      with_items:
          - localhost
          - 127.0.0.1
          - ::1
# 
    - name: configure firewalld
      firewalld:
        port: 3306/tcp
        zone: public
        state: enabled
        permanent: true
#
    - name: add bindaddress
      template: src=templates/bindaddress.cnf.j2 dest=/etc/my.cnf.d/bindaddress.cnf owner=root group=root mode=0644
#
    - name: restart service
      service:
       name: mysqld
       enabled: yes
       state: restarted