---
- hosts: webcluster
  become: True
  become_user: root
  vars_files:
    - vars/nginx.yml
  vars:
   tls_enabled: True
   php_enabled: True
#
# Main Tasks list
#
  tasks:
    - name: wait for ssh server to be running
      local_action: wait_for port=22 host="{{ inventory_hostname }}" search_regex=OpenSSH
#
    - name: Install EPEL7 Repository
      yum:
        name: 'epel-release'
        state: latest
        update_cache: yes
#
    - name: copy epel repo files
      copy: src=files/{{ item }} dest=/etc/yum.repos.d mode="0644"
      with_items:
         - epel.repo
         - epel-testing.repo
#
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: install nginx
      yum:
        name: nginx
        state: latest

    - name: copy config file
      template: src=templates/nginx.conf.j2 dest={{ config_file }} mode="0644"

    - name: copy index.html
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: "0644"

    - name: create conf.d  directory
      file: path=/etc/nginx/conf.d state=directory mode="0644"

    - name: create default.d  directory
      file: path=/etc/nginx/default.d state=directory mode="0644"

    - name: create a ssl directory
      file: path=/etc/nginx/ssl state=directory mode="0644"
      when: tls_enabled

    - name: copy key file
      copy: src=files/random_wildmask/random.key dest={{ key_file }} owner=root mode=0600
      when: tls_enabled
      notify:
         - restart nginx

    - name: copy cert file
      copy: src=files/random_wildmask/random.cer dest={{ cert_file }} owner=root mode=0644
      when: tls_enabled
      notify:
         - restart nginx

#    - name: create dhparam file
#      command: openssl dhparam -out dhparam.pem 4096
#      when: tls_enabled
#      args:
#        chdir: /etc/nginx/ssl
#        creates: /etc/nginx/ssl/dhparam.pem

    - name: copy ssl config file
      template: src=templates/ssl.conf.j2 dest={{ ssl_config_file }} mode="0644"
      when: tls_enabled
      notify:
         - restart nginx

    - name: enable http firewalld policies
      firewalld:
        service: http
        permanent: true
        state: enabled
        zone: public

    - name: enable https firewalld policies
      firewalld:
        service: https
        permanent: true
        state: enabled
        zone: public
      when: tls_enabled

    - name: reload firewall
      service:
         name: firewalld
         state: reloaded

  handlers:
     - name: restart nginx
       service: name=nginx enabled=yes state=restarted
