- name: Install PHP-FPM Module
  hosts: webcluster
  order: sorted
  become: True
  become_user: root
  tasks:
    - name: Install php-fpm
      yum:
        name:
         - php-fpm
         - php-devel
         - php-gd
         - php-pear
         - php-curl
         - php-mcrypt
         - php-imap
         - php-apc
         - php-cgi
         - php-mysql
         - php-getid3
         - php-mbstring
         - php-PHPMailer
         - php-IDNA_Convert
         - php-simplepie
         - php-intl
         - php-ldap
         - php-odbc
         - php-xml
         - php-xmlrpc
         - php-snmp
         - php-soap
         - php-pecl-memcache
         - apr
         - apr-util
        state: latest
#
    - name: Update php-fpm www.conf file
      lineinfile:
         state=present
         dest=/etc/php-fpm.d/www.conf
         regexp="{{ item.regexp }}"
         line="{{ item.line }}"
      with_items:
             - { regexp: '^listen = ' , line: 'listen = /var/run/php-fpm.sock' }
             - { regexp: '^user = ' , line: 'user = nginx' }
             - { regexp: '^group = ' , line: 'group = nginx' }
#
    - name: Update php.ini file
      lineinfile:
         state=present
         dest=/etc/php.ini
         regexp="{{ item.regexp }}"
         line="{{ item.line }}"
      with_items:
             - { regexp: 'cgi.fix_pathinfo' , line: 'cgi.fix_pathinfo = 0' }
             - { regexp: 'date.timezone' , line: 'date.timezone = Asia/Almaty' }
             - { regexp: 'register_globals' , line: 'register_globals = 0' }
#
    - name: Enable php-fpm service
      service:
        name: php-fpm
        enabled: yes
        state: started