---
- name: Install EPEL7 Repository
  yum:
    name: 'epel-release'
    state: latest
- name: upgrade all packages
  yum:
    name: '*'
    state: latest
- name: Install MariaDB Repository
  yum_repository:
    name: mariadb
    description: MariaDB Repository
    baseurl: http://yum.mariadb.org/10.2/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: yes
    includepkgs: MariaDB*
